spring:
  application:
    name: SERVICE1
  cloud:
    discovery:
      client:
        simple:
          instances:
            SERVICE1:
              - uri: http://localhost:8081
            SERVICE2:
              - uri: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
